/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package scannette;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import scannette.classeMetier.Scannette;
import util.AccesAPI;

/**
 *
 * @author solen
 */
public class JffConnexion extends javax.swing.JFrame {

    /**
     * Creates new form JffConnexion
     */
    public JffConnexion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jfAdrMail = new javax.swing.JTextField();
        jBtValider = new javax.swing.JButton();
        jBtQuitter = new javax.swing.JButton();
        jpfMDP = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Authentification");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/key.png"))); // NOI18N
        jLabel1.setText("Mot de passe");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 100, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/utilisateur.png"))); // NOI18N
        jLabel2.setText(" Adresse mail");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 100, 30));
        getContentPane().add(jfAdrMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 100, 30));

        jBtValider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/valider.png"))); // NOI18N
        jBtValider.setText("Valider");
        jBtValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtValiderActionPerformed(evt);
            }
        });
        getContentPane().add(jBtValider, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        jBtQuitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/quitter.png"))); // NOI18N
        jBtQuitter.setText("Quitter");
        jBtQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtQuitterActionPerformed(evt);
            }
        });
        getContentPane().add(jBtQuitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, -1));
        getContentPane().add(jpfMDP, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 162, 100, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/ecran.png"))); // NOI18N
        jLabel4.setText("Authentification");
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 230, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images/fondClair.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 410, 140));

        setBounds(0, 0, 479, 292);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtQuitterActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBtQuitterActionPerformed

    private void jBtValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtValiderActionPerformed
        String identite = "";
        String mail = jfAdrMail.getText();
        String mdp = String.valueOf(jpfMDP.getPassword());

        String[] param = {mail, mdp};
        AccesAPI api = new AccesAPI("http://localhost/Formulaire", param);
        ArrayList<String> lesReponses = api.getReponse();

        String message;
        if (lesReponses.get(0).equals("null")) {
            message = "Adresse mail ou mot de passe erroné";
        } else {
            for (String uneReponse : lesReponses) {
                System.out.println("Une reponse: " + uneReponse);
                identite += uneReponse + "";
            }
            message = "Bienvenue " + identite;
            Scannette laScannette = new Scannette(identite);
            JffScannette saisieArticles = new JffScannette(laScannette);
            saisieArticles.setVisible(true);
            dispose();
        }
        JOptionPane.showMessageDialog(null, message);

    }//GEN-LAST:event_jBtValiderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JffConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JffConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JffConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JffConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JffConnexion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtQuitter;
    private javax.swing.JButton jBtValider;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jfAdrMail;
    private javax.swing.JPasswordField jpfMDP;
    // End of variables declaration//GEN-END:variables
}
